# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: sentinel

on:
  push:

env:
  PRODUCT_VERSION: "0.25.1" # or: "latest"

jobs:
  sentinel:
    runs-on: ubuntu-latest
    name: Run Sentinel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `sentinel`
        uses: hashicorp/setup-sentinel@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `sentinel init`
        id: init
        run: "sentinel test"
